apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vb7r88ica-python
  janus-idp.io/tekton: vb7r88ica-python
  backstage.io/kubernetes-id: vb7r88ica-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vb7r88ica-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
