apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vb7r88ica-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vb7r88ica-python 
  name: vb7r88ica-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vb7r88ica-python 
